Update linux.yml

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -25,21 +25,6 @@ jobs:
       BIN_NAME: listenmoe
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-tags: true
-          fetch-depth: 0
-
-      - name: Debug git tags
-        run: |
-          git config --global --add safe.directory "$GITHUB_WORKSPACE"
-          git status
-          echo "--- tags ---"
-          git tag --list
-          echo "--- describe ---"
-          git describe --tags --abbrev=0 || echo "git describe failed"
-  
       - name: Install build deps
         run: |
           dnf -y update
@@ -54,6 +39,21 @@ jobs:
           echo "$HOME/.cargo/bin" >> $GITHUB_PATH
           "$HOME/.cargo/bin/rustup" target add x86_64-unknown-linux-gnu
           "$HOME/.cargo/bin/rustup" target add aarch64-unknown-linux-gnu
+
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-tags: true
+          fetch-depth: 0
+
+      - name: Debug git tags
+        run: |
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"
+          git status
+          echo "--- tags ---"
+          git tag --list
+          echo "--- describe ---"
+          git describe --tags --abbrev=0 || echo "git describe failed"
 
       - name: Build (release)
         run: cargo build --release --target ${{ matrix.target }} --features setup
